### ISSUE TITLE
Adding Authentication To Your App The Easy Way ~15 minutes

### ISSUE THREAD

**Issue by 0xpbj** [JAMStackSF/JAMStackSF#2]
**Abstract:** _Adding Authentication To Your App The Easy Way_ - Authentication is a major pain point in the decentralized (Web3) app landscape and still in Web2 space. SimpleID was born from our team's experience building the first mobile decentralized messenger (Stealthy), and one of the most popular dApps: Graphite Docs.

In this talk, I'll explain how we help app developers add decentralized authentication and storage in 10 minutes or less, while reducing friction for end-user sign ups. Learning about blockchain technology will be very beneficial for developers professionally and personally as the technology becomes increasingly prevalent. The talk will give the audience the pain points and issues faced by end-users, crypto devs, and web devs.

See our recent post on [HackerNoon](https://hackernoon.com/add-authentication-and-storage-to-your-app-in-10-minutes-ic2h32d1x).

**Bio:** Prabhaav Bhardwaj, Co-Founder Stealthy Inc. Developer for 10+ years, launched first decentralized messenger at [TechCrunch Disrupt](https://techcrunch.com/2018/09/05/stealthy-wants-to-become-the-wechat-of-blockchain-apps/). Previously worked for Xilinx Inc., Mentor Graphics. Built back-end, front-end, web, mobile apps, digital analyzers in Java/C++. Started my career building FPGA design tools and now am trying to help the burgeoning decentralized technology sector. My hobbies: snowboarding, chess, TLC shows.

**Comment by tessamero** [comment]
Hi @prabhaav , I re-reviewed the upcoming schedule and looks like our next opening slot is in November. If you really want to speak earlier, I think I can squeeze it in for September. (The second speaker is still pending talk information).

Let me know if this works for you!

**Comment by 0xpbj** [comment]
I thought this lightning talk was for the pre-conference event: https://www.meetup.com/jamstack-sf/events/263683377/ or is that a different one?

**Comment by tessamero** [comment]
For that, we will be inviting speakers from the JAMStackSF CFPs, but if we have a slot open after, we can consider this. We are still working on specifically what kind of talks we will be accepting and who we are inviting. :)

**Comment by 0xpbj** [comment]
Ok, gotcha. We'd prefer the September meetup 👍

**Comment by tessamero** [comment]
Great. I have updated the September meetup with your information: https://www.meetup.com/jamstack-sf/events/263204180/

Closing and good to go :)

**Comment by tessamero** [comment]
See you tonight!



Tessa Mero
