### ISSUE TITLE
Call authenticated APIs from your JAMStack app ~ 25 minutes

### ISSUE THREAD

**Issue by jplace** [JAMStackSF/JAMStackSF#3]
**Abstract:** It's simple to call APIs from your JAM stack app as long as your APIs are unauthenticated. As soon as your APIs need to securely know a user's identity, you must figure out how to add sign-in and session management to your app. It's hard to implement these features correctly and, even worse, it's very easy to implement them insecurely without realizing.
  Transposit offers an SDK that addresses this challenge, but building it wasn't easy. We thoroughly researched browser cookie policies and cross-domain request security before our initial attempt at an implementation. Even so, our testing revealed that our implementation was broken: it worked reliably in Chrome, but occasionally failed in Safari.
  My talk is a post-mortem on our initial SDK design. I'll go in-depth on why we thought our SDK was secure, and then what flaws caused it to fail in Safari. After, I'll discuss the implementation we actually shipped and why it works. Topics include OAuth, cookie security and CSRF mitigation. Our lessons learned are sure to help anyone thinking about sign-in, authenticated APIs and security in their JAM stack apps.

Our working SDK is now available here: https://github.com/transposit/transposit-js-sdk.

**Bio:** Jordan is a founding engineer at Transposit where he has worked across the stack on infrastructure, testing and product security. He thinks a lot about how to write code that provides business value and isn't scary to change often.

**Comment by tessamero** [comment]
Hello @jplace ! Would you be interested in presenting on November 20th evening? Otherwise the next available date is January to present. Let me know what works for you and happy to make things happen!

**Comment by jplace** [comment]
November 20th works for me! It's on my calendar.

**Comment by tessamero** [comment]
Great, I have included your information on our November event here: https://www.meetup.com/jamstack-sf/events/263813927/.

I will be hosting this meetup so I will see you there. Please email me at tessamero@gmail.com to follow up when the time comes closer.

Closing :)
